---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
setwd("/Users/kavyareddygujjula/Documents/Activity")

rm(list = ls())
dataFile <- ("/Users/kavyareddygujjula/Documents/Activity/activity.csv/")

activity <- read.csv("activity.csv", colClasses = c("numeric", "character", "numeric"))
head(activity)

names(activity)

library(lattice)

activity$date <- as.Date(activity$date, "%Y-%m-%d")

## What is mean total number of steps taken per day?

StepsTotal <- aggregate(steps ~ date, data=activity, sum, na.rm= TRUE)

# Construct a Histogram

hist(StepsTotal$steps, main = "Total steps by day", xlab = "day", ylab="Frequency", col="blue")


## What is the average daily activity pattern?
#calculating mean
mean(StepsTotal$steps)
#calculating median
median(StepsTotal$steps)

time_series <- tapply(activity$steps, activity$interval, mean, na.rm = TRUE)

## Plot 

plot(row.names(time_series), time_series, type = "l", xlab = "5 minute interval",
     ylab = "Average of all Days",
     main = "Average steps taken", col = "green")
     
max_interval <- which.max(time_series)
names(max_interval)

## Imputing missing values

StepsAverage <- aggregate(steps ~ interval, data = activity, FUN = mean)
fillNA <- numeric()
for (i in 1:nrow(activity)) {
  obs <- activity[i, ]
  if (is.na(obs$steps)) {
    steps <- subset(StepsAverage, interval == obs$interval)$steps
  } else {
    steps <- obs$steps
  }
  fillNA <- c(fillNA, steps)
}

new_activity <- activity
new_activity$steps <- fillNA

## Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

StepsTotal2 <- aggregate(steps ~ date, data = new_activity, sum, na.rm = TRUE)

## Constructing Histogram
hist(StepsTotal2$steps, main = "Daily Total Steps", xlab = "day", col = "#CCCCFF")


## Calculating mean
mean(StepsTotal2$steps)

##Calculating media
median(StepsTotal2$steps)


## Are there differences in activity patterns between weekdays and weekends?

day <- weekdays(activity$date)
daylevel <- vector()
for (i in 1:nrow(activity)) {
  if (day[i] == "Saturday") {
    daylevel[i] <- "Weekend"
  } else if (day[i] == "Sunday") {
    daylevel[i] <- "Weekend"
  } else {
    daylevel[i] <- "Weekday"
  }
}
activity$daylevel <- daylevel
activity$daylevel <- factor(activity$daylevel)

stepsByDay <- aggregate(steps ~ interval + daylevel, data = activity, mean)
names(stepsByDay) <- c("interval", "daylevel", "steps")

xyplot(steps ~ interval | daylevel, stepsByDay, type = "l", layout = c(1, 2), 
       xlab = "Interval", ylab = "Number of steps", col=c("#6600CC"))
